"""empty message

Revision ID: 057ba491ff73
Revises: 54b4e83c394b
Create Date: 2016-01-24 20:11:22.634000

"""

# revision identifiers, used by Alembic.
revision = '057ba491ff73'
down_revision = '54b4e83c394b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    ### end Alembic commands ###
