"""empty message

Revision ID: 0891b6f6b647
Revises: 6dc7aae9ef96
Create Date: 2016-01-24 17:14:53.754000

"""

# revision identifiers, used by Alembic.
revision = '0891b6f6b647'
down_revision = '6dc7aae9ef96'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orgfor')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgfor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('orgFor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], [u'events.id'], name=u'orgfor_event_id_fkey'),
    sa.ForeignKeyConstraint(['orgFor'], [u'clubs.id'], name=u'orgfor_orgFor_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'orgfor_pkey')
    )
    ### end Alembic commands ###
