"""empty message

Revision ID: 24e1693032d0
Revises: None
Create Date: 2016-01-24 19:56:12.267000

"""

# revision identifiers, used by Alembic.
revision = '24e1693032d0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clubName', sa.String(), nullable=False),
    sa.Column('aboutClub', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gcmids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.ARRAY(String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('currentAdmin', sa.Boolean(), nullable=True),
    sa.Column('activeStatus', sa.Boolean(), nullable=True),
    sa.Column('isVerified', sa.Boolean(), nullable=True),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('rollNo', sa.String(), nullable=False),
    sa.Column('emailId', sa.String(), nullable=True),
    sa.Column('mobNo', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emailId'),
    sa.UniqueConstraint('mobNo'),
    sa.UniqueConstraint('rollNo'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('club_admins',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventName', sa.String(), nullable=True),
    sa.Column('eventInfo', sa.String(), nullable=True),
    sa.Column('startDateTime', sa.DateTime(), nullable=True),
    sa.Column('endDateTime', sa.DateTime(), nullable=True),
    sa.Column('lastRegDateTime', sa.DateTime(), nullable=True),
    sa.Column('totalSeats', sa.Integer(), nullable=True),
    sa.Column('occupiedSeats', sa.Integer(), nullable=True),
    sa.Column('leftSeats', sa.Integer(), nullable=True),
    sa.Column('eventVenue', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('createdBy', sa.Integer(), nullable=True),
    sa.Column('activeStatus', sa.Boolean(), nullable=True),
    sa.Column('imageLink', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_clubs',
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('club_events',
    sa.Column('clubs_id', sa.Integer(), nullable=True),
    sa.Column('events_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clubs_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['events_id'], ['events.id'], )
    )
    op.create_table('contacts_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contactName', sa.String(), nullable=True),
    sa.Column('contactNumber', sa.BigInteger(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orgby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orgBy', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['orgBy'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_events',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_events')
    op.drop_table('orgby')
    op.drop_table('contacts_events')
    op.drop_table('club_events')
    op.drop_table('user_clubs')
    op.drop_table('events')
    op.drop_table('club_admins')
    op.drop_table('users')
    op.drop_table('test')
    op.drop_table('gcmids')
    op.drop_table('clubs')
    ### end Alembic commands ###
