"""empty message

Revision ID: 294ff9583fee
Revises: bf743841ac41
Create Date: 2016-02-07 15:55:56.972000

"""

# revision identifiers, used by Alembic.
revision = '294ff9583fee'
down_revision = 'bf743841ac41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('clubImage', sa.String(), nullable=True))
    op.add_column('notice', sa.Column('createdBy', sa.Integer(), nullable=True))
    op.add_column('notice', sa.Column('createdTime', sa.DateTime(), nullable=True))
    op.add_column('notice', sa.Column('noticeTitle', sa.String(), nullable=True))
    op.add_column('notice', sa.Column('updatedTime', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'notice', 'users', ['createdBy'], ['id'])
    op.drop_column('notice', 'noticeName')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('noticeName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notice', type_='foreignkey')
    op.drop_column('notice', 'updatedTime')
    op.drop_column('notice', 'noticeTitle')
    op.drop_column('notice', 'createdTime')
    op.drop_column('notice', 'createdBy')
    op.drop_column('clubs', 'clubImage')
    ### end Alembic commands ###
