"""empty message

Revision ID: 2f1a68e6f320
Revises: 7416de6732cd
Create Date: 2016-01-27 18:13:28.831000

"""

# revision identifiers, used by Alembic.
revision = '2f1a68e6f320'
down_revision = '7416de6732cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('scheduler_ids', postgresql.ARRAY(sa.String()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'scheduler_ids')
    ### end Alembic commands ###
