"""empty message

Revision ID: 435f3e06c40d
Revises: 3ffc786ed329
Create Date: 2016-02-11 15:13:33.431000

"""

# revision identifiers, used by Alembic.
revision = '435f3e06c40d'
down_revision = '3ffc786ed329'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_events', sa.Column('contactNumbejhr', sa.String(), nullable=True))
    op.drop_column('contacts_events', 'contactNumber')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_events', sa.Column('contactNumber', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('contacts_events', 'contactNumbejhr')
    ### end Alembic commands ###
