"""empty message

Revision ID: 4adc1bc7a3af
Revises: faefe1869100
Create Date: 2016-01-25 17:13:36.845000

"""

# revision identifiers, used by Alembic.
revision = '4adc1bc7a3af'
down_revision = 'faefe1869100'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hostelName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hostelite_or_localite', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hostelite_or_localite')
    op.drop_column('users', 'hostelName')
    ### end Alembic commands ###
