"""empty message

Revision ID: 6dc7aae9ef96
Revises: bfaec01a51a0
Create Date: 2016-01-23 13:53:11.770000

"""

# revision identifiers, used by Alembic.
revision = '6dc7aae9ef96'
down_revision = 'bfaec01a51a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    ### end Alembic commands ###
