"""empty message

Revision ID: 73dc09f67649
Revises: 9f85594d7908
Create Date: 2016-01-25 00:32:40.962000

"""

# revision identifiers, used by Alembic.
revision = '73dc09f67649'
down_revision = '9f85594d7908'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcmids', sa.Column('data', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('gcmids', 'dataa')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcmids', sa.Column('dataa', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('gcmids', 'data')
    ### end Alembic commands ###
