"""empty message

Revision ID: 7416de6732cd
Revises: f5e49045ff75
Create Date: 2016-01-27 10:45:45.783000

"""

# revision identifiers, used by Alembic.
revision = '7416de6732cd'
down_revision = 'f5e49045ff75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hostelName', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hostelName')
    ### end Alembic commands ###
