"""link

Revision ID: 771c6896715e
Revises: None
Create Date: 2016-01-20 17:33:47.122000

"""

# revision identifiers, used by Alembic.
revision = '771c6896715e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('imageLink', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'imageLink')
    ### end Alembic commands ###
