"""empty message

Revision ID: 905064992630
Revises: c1dcbefacda5
Create Date: 2016-01-26 11:41:25.774000

"""

# revision identifiers, used by Alembic.
revision = '905064992630'
down_revision = 'c1dcbefacda5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('imageB64', sa.Text(), nullable=True))
    op.alter_column('users', 'rollNo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'rollNo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('events', 'imageB64')
    ### end Alembic commands ###
