"""empty message

Revision ID: 910359e71599
Revises: f716052d47e1
Create Date: 2016-01-31 15:21:50.063000

"""

# revision identifiers, used by Alembic.
revision = '910359e71599'
down_revision = 'f716052d47e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orgby', sa.Column('version', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orgby', 'version')
    ### end Alembic commands ###
