"""empty message

Revision ID: 9de10b78707a
Revises: fa0b0d7bf7f7
Create Date: 2016-02-02 15:10:07.336000

"""

# revision identifiers, used by Alembic.
revision = '9de10b78707a'
down_revision = 'fa0b0d7bf7f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('notifMessage', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'notifMessage')
    ### end Alembic commands ###
