"""empty message

Revision ID: 9f85594d7908
Revises: d421580f3d80
Create Date: 2016-01-24 20:17:38.567000

"""

# revision identifiers, used by Alembic.
revision = '9f85594d7908'
down_revision = 'd421580f3d80'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcmids', sa.Column('dataa', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('gcmids', 'data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gcmids', sa.Column('data', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('gcmids', 'dataa')
    ### end Alembic commands ###
