"""empty message

Revision ID: a5d845ca15f3
Revises: bec722baa6c1
Create Date: 2016-02-01 23:08:31.342000

"""

# revision identifiers, used by Alembic.
revision = 'a5d845ca15f3'
down_revision = 'bec722baa6c1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'scheduler_ids')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('scheduler_ids', postgresql.ARRAY(VARCHAR()), autoincrement=False, nullable=True))
    ### end Alembic commands ###
