"""empty message

Revision ID: bec722baa6c1
Revises: f693d3abfc0a
Create Date: 2016-02-01 23:00:34.068000

"""

# revision identifiers, used by Alembic.
revision = 'bec722baa6c1'
down_revision = 'f693d3abfc0a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('scheduler_ids', postgresql.ARRAY(sa.String()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'scheduler_ids')
    ### end Alembic commands ###
