"""empty message

Revision ID: bf743841ac41
Revises: None
Create Date: 2016-02-06 12:30:26.067000

"""

# revision identifiers, used by Alembic.
revision = 'bf743841ac41'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('createdTime', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updatedTime', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updatedTime')
    op.drop_column('users', 'createdTime')
    ### end Alembic commands ###
