"""empty message

Revision ID: c38fda84c4bf
Revises: 2f1a68e6f320
Create Date: 2016-01-28 20:41:52.537000

"""

# revision identifiers, used by Alembic.
revision = 'c38fda84c4bf'
down_revision = '2f1a68e6f320'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_events', sa.Column('contactEmail', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts_events', 'contactEmail')
    ### end Alembic commands ###
