"""empty message

Revision ID: c6a4acd53277
Revises: 457c0dab0129
Create Date: 2016-01-24 17:37:32.324000

"""

# revision identifiers, used by Alembic.
revision = 'c6a4acd53277'
down_revision = '457c0dab0129'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dataa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'test_pkey')
    )
    ### end Alembic commands ###
