"""empty message

Revision ID: cabaec8fabf8
Revises: 771c6896715e
Create Date: 2016-01-23 11:16:08.215000

"""

# revision identifiers, used by Alembic.
revision = 'cabaec8fabf8'
down_revision = '771c6896715e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    op.drop_column('users', 'isadmin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isadmin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'isAdmin')
    ### end Alembic commands ###
