"""empty message

Revision ID: d421580f3d80
Revises: 057ba491ff73
Create Date: 2016-01-24 20:15:28.985000

"""

# revision identifiers, used by Alembic.
revision = 'd421580f3d80'
down_revision = '057ba491ff73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dataa', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'test_pkey')
    )
    ### end Alembic commands ###
