"""empty message

Revision ID: f693d3abfc0a
Revises: 910359e71599
Create Date: 2016-02-01 20:00:24.900000

"""

# revision identifiers, used by Alembic.
revision = 'f693d3abfc0a'
down_revision = '910359e71599'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verifiedNotifs', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notverifiedNotifs', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'events', sa.Column('notifOne', sa.DateTime(), nullable=True))
    op.add_column(u'events', sa.Column('notifTwo', sa.DateTime(), nullable=True))
    op.add_column(u'events', sa.Column('schedulerList', postgresql.ARRAY(sa.String()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'events', 'schedulerList')
    op.drop_column(u'events', 'notifTwo')
    op.drop_column(u'events', 'notifOne')
    op.drop_table('schedule')
    ### end Alembic commands ###
