"""empty message

Revision ID: f716052d47e1
Revises: c38fda84c4bf
Create Date: 2016-01-31 12:02:44.168000

"""

# revision identifiers, used by Alembic.
revision = 'f716052d47e1'
down_revision = 'c38fda84c4bf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('noticeName', sa.String(), nullable=True),
    sa.Column('aboutNotice', sa.String(), nullable=True),
    sa.Column('noticeImage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'events', sa.Column('eventColorHex', sa.String(), nullable=True))
    op.drop_column(u'events', 'scheduler_ids')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'events', sa.Column('scheduler_ids', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column(u'events', 'eventColorHex')
    op.drop_table('notice')
    ### end Alembic commands ###
