"""empty message

Revision ID: fa0b0d7bf7f7
Revises: a5d845ca15f3
Create Date: 2016-02-02 01:09:36.316000

"""

# revision identifiers, used by Alembic.
revision = 'fa0b0d7bf7f7'
down_revision = 'a5d845ca15f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('eventPrizeMoney', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('eventRegFees', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'eventRegFees')
    op.drop_column('events', 'eventPrizeMoney')
    ### end Alembic commands ###
