"""empty message

Revision ID: faefe1869100
Revises: 73dc09f67649
Create Date: 2016-01-25 11:29:34.141000

"""

# revision identifiers, used by Alembic.
revision = 'faefe1869100'
down_revision = '73dc09f67649'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('clubName', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'clubName')
    ### end Alembic commands ###
